# Generated by Django 4.2.15 on 2024-08-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_defect_updated_at_alter_defect_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
