# Generated by Django 4.2.15 on 2024-10-30 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_bug_attachment_alter_epic_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='issueType',
            field=models.CharField(choices=[('EPIC', 'epic'), ('STORY', 'story'), ('TASK', 'task'), ('BUG', 'bug'), ('SUBTASK', 'subtask')], default='EPIC', max_length=15),
        ),
        migrations.AddField(
            model_name='epic',
            name='issueType',
            field=models.CharField(choices=[('EPIC', 'epic'), ('STORY', 'story'), ('TASK', 'task'), ('BUG', 'bug'), ('SUBTASK', 'subtask')], default='EPIC', max_length=15),
        ),
        migrations.AddField(
            model_name='story',
            name='issueType',
            field=models.CharField(choices=[('EPIC', 'epic'), ('STORY', 'story'), ('TASK', 'task'), ('BUG', 'bug'), ('SUBTASK', 'subtask')], default='EPIC', max_length=15),
        ),
        migrations.AddField(
            model_name='subtask',
            name='issueType',
            field=models.CharField(choices=[('EPIC', 'epic'), ('STORY', 'story'), ('TASK', 'task'), ('BUG', 'bug'), ('SUBTASK', 'subtask')], default='EPIC', max_length=15),
        ),
        migrations.AddField(
            model_name='task',
            name='issueType',
            field=models.CharField(choices=[('EPIC', 'epic'), ('STORY', 'story'), ('TASK', 'task'), ('BUG', 'bug'), ('SUBTASK', 'subtask')], default='EPIC', max_length=15),
        ),
    ]
