# Generated by Django 4.2.15 on 2024-08-24 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_bug_tags_task_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='version',
            field=models.CharField(default='1.0.0', max_length=10),
        ),
    ]
