# Generated by Django 4.2.15 on 2024-08-25 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_task_story_subtask'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubTask',
        ),
    ]
