# Generated by Django 4.2.15 on 2024-08-26 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0015_alter_bug_tags_alter_story_tags_alter_subtask_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='bug',
            name='target_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='subtask',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='subtask',
            name='target_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='target_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='target_date',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='Epic',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=15)),
                ('status', models.CharField(choices=[('TO_DO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='TO_DO', max_length=15)),
                ('attachment', models.FileField(upload_to='attachment/')),
                ('start_date', models.DateField(null=True)),
                ('target_date', models.DateField(null=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_assigned_to', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
                ('tags', models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_tags', to='api.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='bug',
            name='epic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.epic'),
        ),
        migrations.AddField(
            model_name='story',
            name='epic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.epic'),
        ),
        migrations.AddField(
            model_name='task',
            name='epic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.epic'),
        ),
    ]
