import type { Metadata } from "next";
import localFont from "next/font/local";
import '../globals.css';
import { LayoutDashboard, NotebookPen, UserRoundPen, Settings, Home } from "lucide-react";
import { SideBarDesktop } from "@/components/sidebar/sidebar-desktop";
import { SideBar } from "@/components/sidebar/sidebar";
import { Header } from "@/components/header/Header";
import { ThemeProvider } from "@/components/ThemeModes/ThemeProvider";
import { AuthProvider } from "@/context/AuthContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function LoginLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <div className="h-full">
      {children}
    </div>
  
  );
}

/*
  <div className="absolute left-0 w-1/6 h-full">
    <SideBarFunction />
  </div>

  <div className="absolute right-0 w-5/6 h-full flex flex-col justify-center">
    {children}
  </div>
*/